config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :blogs
    resources :communities
    resources :events
  end

  resources :blogs, only: :show
  # mount Fae below your admin namespec
  mount Fae::Engine => '/admin'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#landing"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  include Fae::BaseModelConcern

  validates :title, :date_of_news, :content, :active,  presence: true
  validates :slug, presence: true, uniqueness: true

  has_fae_image :cover_image

  def fae_display_field
    title
  end

  def to_param
    slug
  end
end

app/models/community.rb
class Community < ApplicationRecord
  include Fae::BaseModelConcern

  validates :name, :link, :community_type, :active,  presence: true

  validates :link, Fae.validation_helpers.url

  def fae_display_field
    name
  end


end

app/models/concerns/fae/authorization_concern.rb
module Fae
  module AuthorizationConcern
    extend ActiveSupport::Concern
    module ClassMethods

      # Use the access_map to define any controllers that need any special authorization
      # Fae comes with three default roles:
      # - super admin: CRUD all objects, INCLUDING users and root settings
      # - admin: CRUD all objects, INCLUDING users and EXCLUDING root settings
      # - users: CRUD all objects, EXCLUDING users and root settings

      # each item should have a string key of the plural controller name and
      # an array of role names for the value
      # use "content_blocks/#{page_name}" for content blocks

      # example:
      # {
      #  'people' => ['super admin', 'admin'],
      #  'content_blocks/about_us' => ['super admin']
      # }
      def access_map
        {}
      end

    end
  end
end

app/models/concerns/fae/navigation_concern.rb
module Fae
  module NavigationConcern
    extend ActiveSupport::Concern

    # define the navigation structure in this file
    # example structure:
    #
    # def structure
    #   [
    #     item('Top Nav Item 1', subitems: [
    #       item('Top Nav Dropdown Item 1', class: 'custom-class', path: some_named_route_path),
    #       item('Top Nav Dropdown Item 2', subitems: [
    #         item('Side Nav Item 1', subitems: [
    #           item('Side Nav Nested Item', path: some_named_route_path)
    #         ]),
    #         item('Side Nav Item 1', path: some_named_route_path)
    #       ]),
    #     ]),
    #     item('Pages', subitems: [
    #       item('Home', path: fae.edit_content_block_path('home')),
    #       item('About Us', path: fae.edit_content_block_path('about_us'))
    #     ])
    #   ]
    # end

    def structure
      [
        item('最新消息', path: admin_blogs_path),
        item('活動列表', path: admin_events_path),
        item('相關社群', path: admin_communities_path),
        # scaffold inject marker
      ]
    end

  end
end

app/models/event.rb
class Event < ApplicationRecord
  include Fae::BaseModelConcern

  validates :title, :location, :start_time, :end_time, :description,  presence: true

  validates :apply_link, Fae.validation_helpers.url

  def fae_display_field
    title
  end

  has_fae_image :cover_image


end

app/models/seo.rb
# frozen_string_literal: true

class SEO
  attr_accessor :title, :description, :url, :image, :type

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value) if respond_to?("#{name}=")
    end
  end

  def to_meta
    {
      title: title,
      description: description
    }
  end

  def to_google
    {
      name: title,
      description: description,
      image: image
    }
  end

  def to_open_graph
    {
      title: title,
      description: description,
      image: image,
      url: url,
      type: type
    }
  end
end

app/controllers/admin/blogs_controller.rb
module Admin
  class BlogsController < Fae::BaseController

    def index
      @items = Blog.order('date_of_news DESC')
    end

    def new
      super
      @item.date_of_news = Time.zone.now
    end

    private

    def build_assets
      @item.build_cover_image if @item.cover_image.blank?
    end
  end
end

app/controllers/admin/communities_controller.rb
module Admin
  class CommunitiesController < Fae::BaseController

    def index
      @items = Community.order('id')
    end

  end
end

app/controllers/admin/events_controller.rb
module Admin
  class EventsController < Fae::BaseController

    def index
      @items = Event.order('start_on DESC')
    end

    private

    def build_assets
      @item.build_cover_image if @item.cover_image.blank?
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_locale

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def show
    @blog = Blog.find_by(slug: params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def landing
    @blogs = Blog.where(active: true).order(date_of_news: :desc).order(created_at: :desc)
    @events = Event.order(start_on: :desc)
    @events_active = Event.where(active: true)
    @events_ended = Event.where(active: false)
    @communities = Community.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = {
      filter_html: true,
      hard_wrap: true,
      link_attributes: { target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true,
      prettify: true
    }

    extensions = {
      autolink: true,
      superscript: true,
      highlight: true,
      no_intra_emphasis: true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end

  def home_page_loaded?
    request.path == root_path || request.headers['HTTP_TURBOLINKS_REFERRER'].present?
  end

  def page_title
    [content_for(:title), t('landing.site')].compact.join(' | ')
  end

  def page_description
    content_for(:description) || t('landing.description')
  end

  def page_image
    content_for(:image) || 'og_image.png'
  end

  def page_type
    return :website if request.path == root_path
    :article
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/seo_helper.rb
# frozen_string_literal: true

module SeoHelper
  def seo_meta_tags
    capture do
      meta_tags(seo.to_meta)
      og_meta_tags(seo.to_open_graph)
      google_meta_tags(seo.to_google)
      twitter_meta_tags
    end
  end

  private

  # http://ogp.me/
  def og_meta_tags(options = {})
    meta_tags(options) do |name, value|
      tag(:meta, property: "og:#{name}", content: value)
    end
  end

  # http://schema.org/
  def google_meta_tags(options = {})
    meta_tags(options) do |name, value|
      tag(:meta, itemprop: name, content: value)
    end
  end

  def twitter_meta_tags(options = {})
    default = {
      card: 'summary',
      site: '@rubytaiwan'
    }

    meta_tags(default.merge(options)) do |name, value|
      tag(:meta, name: "twitter:#{name}", content: value)
    end
  end

  def meta_tags(**hash, &_block)
    hash.each do |name, value|
      if block_given?
        concat yield(name, value)
      else
        concat tag(:meta, name: name, content: value)
      end
    end
  end

  def seo
    @seo ||= SEO.new(
      title: page_title,
      description: page_description,
      image: image_url(page_image),
      url: request.url,
      type: page_type
    )
  end
end

app/views/admin/blogs/_form.html.slim
= simple_form_for([:admin, @item]) do |f|
  header.content-header.js-content-header
    == render 'fae/shared/form_header', header: @klass_name
  == render 'fae/shared/errors'

  main.content
    = fae_input f, :title, label: '標題', input_class: 'slugger'
    = fae_input f, :slug, label: '網址', placeholder: 'some-blog-post'
    = fae_datepicker f, :date_of_news, label: '日期'
    = fae_input f, :content, markdown: true, markdown_supported: true, label: '內文'
    = fae_radio f, :active, type: 'inline', label: '發佈於首頁'


    = fae_image_form f, :cover_image, label: '封面照片', alt_label: '封面照片替代文字', alt_helper_text: '請輸入有助於 SEO 的替代文字'

app/views/admin/blogs/edit.html.slim
== render 'form'

app/views/admin/blogs/index.html.slim
== render 'fae/shared/index_header', title: @klass_humanized.pluralize.titleize

main.content
  table.js-sort-column
    thead
      tr
        th.width-50 data-sorter="false"
        th.width-150.text-center data-sorter="false" 封面照片
        th 標題
        th.width-120.text-center 日期
        th.width-140.text-center 發佈於首頁
        th.width-170.text-center 更新時間
        th.-action data-sorter="false"

    tbody
      - if @items.present?
        - @items.each_with_index do |item, index|
          tr id=fae_sort_id(item)
            td.text-center = index + 1
            td = fae_index_image item.cover_image, edit_admin_blog_path(item.id)
            td = link_to item.fae_display_field, edit_admin_blog_path(item.id)
            td.text-center = item.date_of_news.strftime("%Y.%m.%d")
            td = fae_toggle item, :active
            td.text-center = item.updated_at.strftime("%Y-%m-%d at %H:%M")
            td = fae_delete_button item, id: item.id
      - else
        tr: td colspan="4" No items found

app/views/admin/blogs/new.html.slim
== render 'form'

app/views/admin/communities/_form.html.slim
= simple_form_for(['admin', @item]) do |f|
  header.content-header.js-content-header
    == render 'fae/shared/form_header', header: @klass_name
  == render 'fae/shared/errors'

  main.content
    = fae_input f, :name, label: '名稱'
    = fae_input f, :link, label: '網址'
    = fae_radio f, :community_type, collection:['Link', 'Facebook' , 'Twitter'], label: '類別'
    = fae_radio f, :active, type: 'inline', label: '顯示於首頁'

app/views/admin/communities/edit.html.slim
== render 'form'

app/views/admin/communities/index.html.slim
== render 'fae/shared/index_header', title: @klass_humanized.pluralize.titleize

main.content
  table.js-sort-column
    thead
      tr
        th.width-50 data-sorter="false"
        th 社群名稱
        th.width-150.text-center 社群類別
        th.width-140.text-center 顯示於首頁
        th.width-170.text-center 更新時間
        th.-action data-sorter="false"

    tbody
      - if @items.present?
        - @items.each_with_index do |item, index|
          tr id=fae_sort_id(item)
            td = index + 1
            td = link_to item.fae_display_field, edit_admin_community_path(item)
            td.text-center = item.community_type
            td = fae_toggle item, :active
            td.text-center = item.updated_at.strftime("%Y-%m-%d at %H:%M")
            td = fae_delete_button item
      - else
        tr: td colspan="3" No items found

app/views/admin/communities/new.html.slim
== render 'form'

app/views/admin/events/_form.html.slim
= simple_form_for(['admin', @item]) do |f|
  header.content-header.js-content-header
    == render 'fae/shared/form_header', header: @klass_name
  == render 'fae/shared/errors'

  main.content
    = fae_input f, :title, label: '活動名稱'
    = fae_input f, :location, label: '活動地點'
    = fae_daterange f, [:start_on, :end_on], label: '活動日期', helper_text: '請先點選開始日期，再點選結束日期。若為當日活動，點選兩次該日期即可。'
    = fae_input f, :start_time, label: '開始時間'
    = fae_input f, :end_time, label: '結束時間'
    = fae_input f, :description, label: '活動簡介'
    = fae_radio f, :need_apply, type: 'inline', label: '是否報名'
    = fae_input f, :apply_link, label: '報名網址'
    = fae_radio f, :active, type: 'inline', label: '活動進行中'


    = fae_image_form f, :cover_image, label: '封面照片', alt_label: '封面照片替代文字', alt_helper_text: '請輸入有助於 SEO 的替代文字'

app/views/admin/events/edit.html.slim
== render 'form'

app/views/admin/events/index.html.slim
== render 'fae/shared/index_header', title: @klass_humanized.pluralize.titleize

main.content
  table.js-sort-column
    thead
      tr
        th.width-50 data-sorter="false"
        th.width-150.text-center data-sorter="false" 封面照片
        th 活動名稱
        th.width-150.text-center 活動日期
        th.width-120.text-center 是否報名
        th.width-120.text-center 活動狀態
        th.width-170.text-center 更新時間
        th.-action data-sorter="false"

    tbody
      - if @items.present?
        - @items.each_with_index do |item, index|
          tr id=fae_sort_id(item)
            td = index + 1
            td = fae_index_image item.cover_image, edit_admin_event_path(item)
            td = link_to item.fae_display_field, edit_admin_event_path(item)
            - if item.start_on != item.end_on
              td.text-center 
                = item.start_on.strftime("%Y.%m.%d")
                | -
                = item.end_on.strftime("%d")
            - else
              td.text-center = item.start_on.strftime("%Y.%m.%d")
            td = fae_toggle item, :need_apply
            td = fae_toggle item, :active
            td.text-center = item.updated_at.strftime("%Y-%m-%d at %H:%M")
            td = fae_delete_button item
      - else
        tr: td colspan="4" No items found

app/views/admin/events/new.html.slim
== render 'form'

app/views/blogs/show.html.slim
- content_for :title, @blog.title
- content_for :description, strip_tags(markdown(@blog.content)).gsub(/\n|\r/, ' ').truncate(150)
- content_for :image, @blog.cover_image&.asset_url
- if home_page_loaded?
  #landing data-turbolinks-permanent=true

#blog-info.hidden
  nav.navbar.navbar-default.navbar-custom
    .container-fluid
      .navbar-header
        button.navbar-toggle data-target="#navbar-collapse" data-toggle="collapse" type="button"
          i.fa.fa-bars
        = link_to root_path, class: 'navbar-brand' do
          = inline_svg 'cover/ruby_taiwan_logotype.svg', title: 'Ruby Taiwan Logotype'

      #navbar-collapse.collapse.navbar-collapse
        ul.nav.navbar-nav.navbar-right
          li.social-media
            = link_to t('social-media.twitter'), target: '_blank' do
              i.fa.fa-twitter aria-hidden="true"
          li.social-media
            = link_to t('social-media.github'), target: '_blank' do
              i.fa.fa-github aria-hidden="true"
          li.social-media
            = link_to t('social-media.facebook'), target: '_blank' do
              i.fa.fa-facebook-official aria-hidden="true"

  - if @blog.cover_image.asset?
    .cover-image
      = image_tag @blog.cover_image.asset.url, title: @blog.title, alt: @blog.cover_image.alt

  .content
    span.content-date = @blog.date_of_news.strftime("%b %d, %Y")
    h1.content-title = @blog.title
    = inline_svg 'icon_ruby.svg'
    = markdown(@blog.content)

#blogs
  #blog-modal.modal
    .modal-dialog role="document"
      .modal-content
        .modal-header
          button.close aria-label="Close" data-dismiss="modal" type="button"
            span aria-hidden="true"  &times;
        .modal-body
          - if @blog.cover_image.asset?
            .cover-image
              = image_tag @blog.cover_image.asset.url, title: @blog.title, alt: @blog.cover_image.alt
          .content
            span.content-date = @blog.date_of_news.strftime("%b %d, %Y")
            h1.content-title = @blog.title
            = inline_svg 'icon_ruby.svg'
            = markdown(@blog.content)

= render 'shared/footer'

app/views/home/_blogs.slim
section#blogs
  .blog-card
    h3.section-title =t('section.blog')
    
    .blog-list
      - if @blogs.present?
        - @blogs.each_with_index do |blog, index|
          .blog class="#{index < 5 ? '' : 'more'}"
            span.blog-date = blog.date_of_news.strftime("%b %d %Y")
            = link_to blog.title, blog, class:"blog-title"
    
    - if @blogs.length >= 5
      button.button-more.blog-more =t('helper.view_more')

app/views/home/_campaigns.slim
section#campaigns

  - t('campaigns').each_with_index do |campaign, index|
    .campaign-card class="#{index.odd? ? 'odd' : 'even'} #{campaign[:id]}"
    
      .campaign-info
        h4.campaign-title = campaign[:title]
        = inline_svg 'icon_ruby.svg'
        p.campaign-desc = campaign[:desc]
        - if campaign[:links].length == 2
          - campaign[:links].each do |key, value|
            = link_to value, target: :_blank, :class => "campaign-link double" do 
              = key
        - if campaign[:links].length == 3
          - campaign[:links].each do |key, value|
            = link_to value, target: :_blank, :class => "campaign-link triple" do 
              = key

      .campaign-photos.carousel.slide data-ride="carousel" id="#{campaign[:id] + '-photo'}"
        /! Indicators
        ol.carousel-indicators
          - campaign[:photo].each_with_index do |photo, index|
            li data-slide-to="#{index}" data-target="#{'#' + campaign[:id] + '-photo'}" class="#{index == 0 ? "active" : ""}"
        / ! Wrapper for slides
        .carousel-inner role="listbox"
          - campaign[:photo].each_with_index do |photo, index|
            .item class="#{index == 0 ? "active" : ""}" id="#{campaign[:id] + '-photo-'}#{index}"
              = image_tag 'campaigns/' + photo, alt: campaign[:title], title: campaign[:title]

app/views/home/_communities.slim
section#communities
  h3.section-title =t('section.communities')

  .communities
    - if @communities.present?
      - @communities.each_with_index do |community, index|
        - if community.active.present?
          .community class="#{index.odd? ? 'odd' : 'even'}"
            = link_to community.link, target: :_blank, :class=> "community-card" do
              .community-info
                = community.name
                - if community.community_type == 'Facebook'
                  i.fa.fa-facebook-official aria-hidden="true"
                - elsif community.community_type == 'Twitter'
                  i.fa.fa-twitter aria-hidden="true"
                - else
                  i.fa.fa-external-link aria-hidden="true"

app/views/home/_cover.slim
#cover
  .ruby_taiwan_cover
    = inline_svg 'cover/cover-sky.svg'
    = inline_svg 'cover/cover-night.svg'
    = inline_svg 'cover/cover-platform_l.svg'
    = inline_svg 'cover/cover-platform_r.svg'
    = inline_svg 'cover/cover-ocean.svg'
    = inline_svg 'cover/cover-ground.svg'

  .ruby_taiwan

    .ruby_taiwan_logo
      = inline_svg 'cover/ruby_taiwan_logo.svg', title: 'Ruby Taiwan Logo'
    .ruby_taiwan_logotype
      = inline_svg 'cover/ruby_taiwan_logotype.svg', title: 'Ruby Taiwan Logotype'
    .ruby_taiwan_year
      p Since 2008
    .ruby_taiwan_social
      = link_to t('social-media.twitter'), target: :_blank, class: "social-links" do
        i.fa.fa-twitter aria-hidden="true"
      = link_to t('social-media.github'), target: :_blank, class: "social-links" do
        i.fa.fa-github aria-hidden="true"
      = link_to t('social-media.facebook'), target: :_blank, class: "social-links" do
        i.fa.fa-facebook-official aria-hidden="true"

app/views/home/_events.slim
section#events
  h3.section-title =t('section.events')

  .events-list
    - if @events.present?
      - if @events_active.blank?
        span.event-empty
          =t('helper.empty_events')
      - @events.each do |event|
        .event-card class="#{event.active ? '' : 'ended'}"
          .event-photo
            - if event.cover_image.asset?
              = image_tag event.cover_image.asset.url, title: event.title, alt: event.cover_image.alt
          .event-info
            - if event.start_on && event.end_on?
              - if event.start_on == event.end_on
                p.event-date = event.start_on.strftime("%Y.%m.%d")
              - else
                p.event-date.period 
                  = event.start_on.strftime("%Y.%m.%d")
                  | -
                  = event.end_on.strftime("%d")
            - if event.apply_link?
              = link_to event.apply_link, target: :_blank, class: "event-title" do
                = event.title
            - else
              p.event-title = event.title
            .event-time
              i.fa.fa-clock-o aria-hidden="true"
              p 
                = event.start_time.strftime("%H:%M")
                | &nbsp;~&nbsp;
                = event.end_time.strftime("%H:%M")
            .event-location
              i.fa.fa-map-marker aria-hidden="true"
              p = event.location
            p.event-desc = event.description
          - if event.active && event.need_apply
            = link_to event.apply_link, target: :_blank, class:'button-apply active' do
              =t('helper.apply_now')
          - elsif event.active.blank?
            .button-apply
              =t('helper.ended_events')
          - else
            .button-apply
              =t('helper.apply_none')

    - else
      span.event-empty
        =t('helper.empty_events')

  - if @events_ended.present?
    button.button-more.events-more =t('helper.order_events')

app/views/home/_subscription.slim
section#subscription
  h3.section-title =t('section.subscription')
  = inline_svg 'icon_ruby.svg'

  .subscription.input-group
    form action="//rubyconf.us14.list-manage.com/subscribe/post?u=f8697172394cf1829922f9d1e&amp;id=81dd266430" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank"
      input.required.form-control placeholder=t('helper.placeholder') name="EMAIL" type="email" required="required"/
      span.input-group-btn
        button.btn type="submit" name="subscribe"
          = t('helper.subscription')

app/views/home/landing.html.slim
#landing data-turbolinks-permanent=true
  = render 'shared/nav'
  = render 'cover'

  .main
    .container-fluid
      = render 'blogs'
      = render 'events'
      = render 'campaigns'
      = render 'communities'
      = render 'subscription'

  = render 'shared/footer'

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8" /
    title = page_title
    = seo_meta_tags
    meta content="yes" name="apple-mobile-web-app-capable" /
    meta content="width=device-width, height=device-height, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport" /
    - unless home_page_loaded?
      meta name="turbolinks-cache-control" content="no-cache"
    = csrf_meta_tags
    = action_cable_meta_tag

    /! Favicons
    link href="/img/favicon.ico" rel=("shortcut icon") type="image/x-icon" /

    /! CSS & JS
    link rel="stylesheet" href="//fonts.googleapis.com/css?family=Montserrat|Lobster"
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true

  body
    = yield

app/views/shared/_footer.slim
#footer
  p 
    | © 2017 Designed &#38; Powered by 
    a href="https://5xruby.tw" 5XRUBY

app/views/shared/_nav.slim
nav#affixNav.navbar.navbar-default.navbar-custom.navbar-fixed-top
  .container-fluid
    .navbar-header.page-scroll
      button.navbar-toggle data-target="#navbar-collapse" data-toggle="collapse" type="button" 
        i.fa.fa-bars
      a.navbar-brand.page-scroll href="#cover"
        = inline_svg 'cover/ruby_taiwan_logotype.svg', title: 'Ruby Taiwan'

    #navbar-collapse.collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-right
        li
          a.page-scroll href="#blogs"  =t('section.blog')
        li
          a.page-scroll href="#events"  =t('section.events')
        li
          a.page-scroll href="#communities"  =t('section.communities')
        li.social-media
          = link_to t('social-media.twitter'), target: '_blank' do
            i.fa.fa-twitter aria-hidden="true"
        li.social-media
          = link_to t('social-media.github'), target: '_blank' do
            i.fa.fa-github aria-hidden="true"
        li.social-media
          = link_to t('social-media.facebook'), target: '_blank' do
            i.fa.fa-facebook-official aria-hidden="true"